# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Change to the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
      - name: Success
        run: echo "Success"

#       - name: Build and Push Docker Image
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         run: |
#           docker build -t tkundra00/node-server:v1 .
#           echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
#           docker push tkundra00/node-server:v1
